/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as CriativosRouteImport } from './routes/criativos'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as IndexRouteImport } from './routes/index'

const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CriativosRoute = CriativosRouteImport.update({
  id: '/criativos',
  path: '/criativos',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/criativos': typeof CriativosRoute
  '/integracoes': typeof IntegracoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/criativos': typeof CriativosRoute
  '/integracoes': typeof IntegracoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRoute
  '/criativos': typeof CriativosRoute
  '/integracoes': typeof IntegracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campanhas' | '/criativos' | '/integracoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campanhas' | '/criativos' | '/integracoes'
  id: '__root__' | '/' | '/campanhas' | '/criativos' | '/integracoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanhasRoute: typeof CampanhasRoute
  CriativosRoute: typeof CriativosRoute
  IntegracoesRoute: typeof IntegracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criativos': {
      id: '/criativos'
      path: '/criativos'
      fullPath: '/criativos'
      preLoaderRoute: typeof CriativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanhasRoute: CampanhasRoute,
  CriativosRoute: CriativosRoute,
  IntegracoesRoute: IntegracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
